[project]
name = "monorepo"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["eevee", "kabigon"]

[tool.uv.workspace]
members = ["src/eevee", "src/kabigon"]

[tool.uv.sources]
eevee = { workspace = true }
kabigon = { workspace = true }
